name: echo issues
on: issues

jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: echo issue
        run: |
          echo "Issue title: ${{ toJSON(github.event.issue.title) }}"
          echo "Issue body: ${{ toJSON(github.event.issue.body) }}"