name: echo issues
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: echo issue
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"